/**
 * scripts/buildDefinitions.mjs
 *
 * Generates src/data/definitions.js — the app-wide child-friendly clue cache.
 *
 * Strategy
 * ─────────
 * 1. Pull every entry from all 6 word-data arrays.
 *    • KS1 sources  (yearBand: null)  → use definitions.ages5to7
 *    • KS2 sources  (yearBand: y3x)   → use definitions.ages7to10
 * 2. Merge with the existing file:
 *    • Database definition wins for any word it covers.
 *    • Existing entries for words NOT in the database are kept verbatim
 *      (safety entries for ambiguous short words that would otherwise get
 *       adult API results — e.g. "joint", "crack", "shoot").
 * 3. Write out a new definitions.js sorted alphabetically within each tier.
 *
 * Usage:
 *   node scripts/buildDefinitions.mjs
 */

import { Y1_WORD_DATA, Y2_WORD_DATA, KS1_GAP_WORDS } from '../src/data/ks1WordData_v14.js';
import { Y34_WORD_DATA, Y56_WORD_DATA, KS2_GAP_WORDS } from '../src/data/ks2WordData_v27.js';
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH   = join(__dirname, '../src/data/definitions.js');

// ── 1. Build the database map ─────────────────────────────────────────────────

const dbMap = new Map(); // word.toLowerCase() → definition string

function ingest(arr, field) {
  for (const entry of arr) {
    if (!entry || !entry.word) continue;
    const def = entry.definitions?.[field];
    if (typeof def === 'string' && def.trim()) {
      dbMap.set(entry.word.toLowerCase(), def.trim());
    }
  }
}

ingest(Y1_WORD_DATA,   'ages5to7');
ingest(Y2_WORD_DATA,   'ages5to7');
ingest(KS1_GAP_WORDS,  'ages5to7');
ingest(Y34_WORD_DATA,  'ages7to10');
ingest(Y56_WORD_DATA,  'ages7to10');
ingest(KS2_GAP_WORDS,  'ages7to10');

console.log(`Database: ${dbMap.size} definitions loaded.`);

// ── 2. Parse existing definitions.js for safety/legacy entries ────────────────
// Extract every   key: 'value',  line with a simple regex so we keep
// manually-curated entries for words that aren't in the word database.

const legacyMap = new Map(); // word → definition (from existing file)

try {
  const src = readFileSync(OUT_PATH, 'utf8');
  // Match lines like:  someword:  'Some definition text',
  // or quoted keys:    'mr':  'A title...',
  const lineRe = /^\s+(?:'([^']+)'|([a-zA-Z_][a-zA-Z0-9_]*)):\s+'((?:[^'\\]|\\.)*)'\s*,?\s*$/gm;
  let m;
  while ((m = lineRe.exec(src)) !== null) {
    const key = (m[1] || m[2]).toLowerCase();
    const val = m[3].replace(/\\'/g, "'");
    legacyMap.set(key, val);
  }
  console.log(`Existing file: ${legacyMap.size} entries parsed.`);
} catch {
  console.log('No existing definitions.js found — starting fresh.');
}

// ── 3. Build the merged output map ────────────────────────────────────────────
// db wins for curriculum words; legacy kept for non-db words.

const merged = new Map([...legacyMap, ...dbMap]); // db overwrites legacy

const dbOnly   = [...merged.keys()].filter(k =>  dbMap.has(k));
const legacyOnly = [...merged.keys()].filter(k => !dbMap.has(k));

console.log(`Output: ${merged.size} total (${dbOnly.length} from database, ${legacyOnly.length} legacy-only).`);

// ── 4. Format output ──────────────────────────────────────────────────────────

function fmtEntry(word, def) {
  // Escape backslashes first, then single quotes in the value
  const escaped = def.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  // Choose key format:
  //   bare identifier for simple lowercase words (a-z0-9 only)
  //   double-quoted key if the word contains a single quote (e.g. aren't)
  //   single-quoted key for everything else (hyphens, numbers, etc.)
  let key;
  if (/^[a-z][a-z0-9]*$/.test(word)) {
    key = word;
  } else if (word.includes("'")) {
    key = `"${word}"`;
  } else {
    key = `'${word}'`;
  }
  // Pad key+colon for readability
  const padded = (key + ':').padEnd(Math.max(key.length + 1, 14));
  return `  ${padded} '${escaped}',`;
}

const dbLines     = dbOnly.sort().map(w => fmtEntry(w, merged.get(w)));
const legacyLines = legacyOnly.sort().map(w => fmtEntry(w, merged.get(w)));

const now = new Date().toISOString().slice(0, 10);

const output = `// Auto-generated by scripts/buildDefinitions.mjs — do not edit by hand.
// Regenerate: node scripts/buildDefinitions.mjs
//
// Source   : ks1WordData_v14.js (ages5to7) + ks2WordData_v27.js (ages7to10)
// Generated: ${now}
// Entries  : ${dbOnly.length} from database + ${legacyOnly.length} legacy-only = ${merged.size} total
//
// Every game that shows a clue to a child (Crossword, Quiz Quest, Hangman,
// Memory Spell, Write It) checks this map first. Only words not present here
// reach the external dictionary API.

const DEFINITIONS = {

  // ── Curriculum words (sourced from word database) ────────────────────────
${dbLines.join('\n')}

${legacyOnly.length > 0 ? `  // ── Legacy / safety entries (not in word database) ────────────────────────
  // Retained to prevent ambiguous short words from hitting the external API.
${legacyLines.join('\n')}
` : ''}};

export default DEFINITIONS;
`;

// ── 5. Write ──────────────────────────────────────────────────────────────────

writeFileSync(OUT_PATH, output, 'utf8');
console.log(`\nWrote ${merged.size} entries → ${OUT_PATH}`);

// ── 6. Sanity checks ──────────────────────────────────────────────────────────

const spot = ['the', 'cat', 'friend', 'because', 'accommodate', 'rhythm'];
console.log('\nSpot-check:');
for (const w of spot) {
  const v = merged.get(w) ?? '*** MISSING ***';
  console.log(`  ${w.padEnd(14)} ${v.slice(0, 70)}`);
}

// Report any curriculum words with no definition (empty in the database)
// KS1 bands: null or "y12". KS2 bands: "y34", "y56", "y3", "y4", "y5", "y6", etc.
const isKS1Band = (yb) => !yb || yb === 'y12';
const emptyInDb = [
  ...Y1_WORD_DATA.map(e => ({ e, field: 'ages5to7' })),
  ...Y2_WORD_DATA.map(e => ({ e, field: 'ages5to7' })),
  ...KS1_GAP_WORDS.map(e => ({ e, field: 'ages5to7' })),
  ...Y34_WORD_DATA.map(e => ({ e, field: 'ages7to10' })),
  ...Y56_WORD_DATA.map(e => ({ e, field: 'ages7to10' })),
  ...KS2_GAP_WORDS.map(e => ({ e, field: 'ages7to10' })),
]
  .filter(({ e, field }) => {
    if (!e || !e.word) return false;
    const def = e.definitions?.[field];
    return !def || !def.trim();
  })
  .map(({ e }) => e)
  .map(e => e.word);

if (emptyInDb.length > 0) {
  console.log(`\nWarning: ${emptyInDb.length} database entries had empty definitions and were skipped:`);
  console.log(' ', emptyInDb.slice(0, 20).join(', ') + (emptyInDb.length > 20 ? ` … (+${emptyInDb.length - 20} more)` : ''));
} else {
  console.log('\nAll database entries have definitions. ✓');
}
